name: PHPUnit

on:
    push:
        branches: [ master ]
    pull_request:
    workflow_dispatch: ~

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Setup PHP
              uses: auto1-oss/setup-php@v2
              with:
                  php-version: '8.1'
                  extensions: mbstring, xml

            - name: Validate composer.json
              run: composer validate

            - name: Install dependencies
              run: composer install --prefer-dist --no-progress --no-suggest

            - name: Run tests
              run: ./vendor/bin/phpunit
